---
- debug:
    var: ansible_date_time.date

- name: update
  ansible.builtin.dnf:
    name: "*"
    state: latest

- name: Importing (free) key
  ansible.builtin.rpm_key:
    state: present
    key: https://rpmfusion.org/keys?action=AttachFile&do=get&target=RPM-GPG-KEY-rpmfusion-free-fedora-2020

- name: Importing (non-free) key
  ansible.builtin.rpm_key:
    state: present
    key: https://rpmfusion.org/keys?action=AttachFile&do=get&target=RPM-GPG-KEY-rpmfusion-nonfree-fedora-2020

- name: install the rpmfusion repo packages
  ansible.builtin.dnf:
    name: "{{ common_repos }}"
    state: present

- name: config set enable termite
  command: rpm --import https://brave-browser-rpm-release.s3.brave.com/brave-core.asc

- name: config set enable termite
  command: dnf copr enable -y skidnik/termite

- name: All the packages I require for my workstation
  package:
    name: "{{ common_packages }}"
    state: present
  ignore_errors: true

- name: Set zsh as default shell
  user:
    name: "{{ user }}"
    shell: /bin/zsh
