_repos:
  default:
    - empty
  Fedora:
    - fedora-workstation-repositories
    - https://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-{{ansible_distribution_major_version}}.noarch.rpm
    - http://download1.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-{{ansible_distribution_major_version}}.noarch.rpm




_packages:
  default: []
  Fedora:
    - '@base-x'
    - '@Common NetworkManager Submodules'
    - '@Development Tools'
    - '@Fonts'
    - '@Hardware Support'
    - '@Multimedia'
    - '@Standard'
    - ansible-lint
    - dnf-plugins-core
    - htop
    - lm_sensors
    - setroubleshoot-server
    - setroubleshoot
    - zsh
    - python3
    - python3-pip
    - elixir
    - neovim
    - exa
    - termite
    - curl
    - lxrandr
    - gimp
    - g++
    - gcc
    - cmake
    - SFML-devel
    - xset
    - sqlite
    - google-chrome-stable
    - lpf-spotify-client

common_repos: "{{ _repos[ansible_distribution] | default(_repos['default']) }}"

common_url_repos: "{{ _repos_url[ansible_distribution] | default(_repos_url['default']) }}"

common_packages: "{{ _packages[ansible_distribution] | default(_packages['default']) }}"

