export WORKON_HOME=~/.virtualenvs
mkdir -p $WORKON_HOME

VIRTUALENVWRAPPER_PYTHON=/usr/bin/python3
source /home/erwanbernard/.local/bin/virtualenvwrapper.sh

# If you come from bash you might have to change your $PATH.
export PATH=$HOME/.bin:$HOME/bin:/usr/local/bin:$HOME/Bureau/pycharm/bin:$HOME/go/bin:$PATH
export PATH=$HOME/git/gitgit/dotfiles/bin:$HOME/.local/bin:/var/lib/snapd/snap:$PATH
export BROWSER=brave-browser
export _JAVA_AWT_WM_NONREPARENTING=1

export PATH=/usr/local/cuda/bin:$PATH
export LD_LIBRARY_PATH=/usr/local/cuda/lib64:$LD_LIBRARY_PATH


# Path to your oh-my-zsh installation.
export LC_ALL="fr_FR.UTF-8"
export LC_CTYPE="fr_FR.UTF-8",
export LC_COLLATE="fr_FR.UTF-8",
export LANG="fr_FR.UTF-8"

export ZSH=~/.oh-my-zsh
export VISUAL="nvim"
export TERM=xterm-256color

export CXX="/usr/bin/g++"
export ERL_AFLAGS="-kernel shell_history enabled"

#python
#export PYTHONSTARTUP=~/.pythonrc

#export for 42 header
#export USER=erwberna
#export MAIL=erwberna@student.fr

# Set name of the theme to load. Optionally, if you set this to "random"
# it'll load a random theme each time that oh-my-zsh is loaded.
# See https://github.com/robbyrussell/oh-my-zsh/wiki/Themes
ZSH_THEME="my_arrow"

# Uncomment the following line to use case-sensitive completion.
# CASE_SENSITIVE="true"

# Uncomment the following line to use hyphen-insensitive completion. Case
# sensitive completion must be off. _ and - will be interchangeable.
# HYPHEN_INSENSITIVE="true"

# Uncomment the following line to disable bi-weekly auto-update checks.
# DISABLE_AUTO_UPDATE="true"

# Uncomment the following line to change how often to auto-update (in days).
# export UPDATE_ZSH_DAYS=13

# Uncomment the following line to disable colors in ls.
# DISABLE_LS_COLORS="true"

# Uncomment the following line to disable auto-setting terminal title.
# DISABLE_AUTO_TITLE="true"

# Uncomment the following line to enable command auto-correction.
# ENABLE_CORRECTION="true"

# Uncomment the following line to display red dots whilst waiting for completion.
# COMPLETION_WAITING_DOTS="true"

# Uncomment the following line if you want to disable marking untracked files
# under VCS as dirty. This makes repository status check for large repositories
# much, much faster.
# DISABLE_UNTRACKED_FILES_DIRTY="true"

# Uncomment the following line if you want to change the command execution time
# stamp shown in the history command output.
# The optional three formats: "mm/dd/yyyy"|"dd.mm.yyyy"|"yyyy-mm-dd"
# HIST_STAMPS="mm/dd/yyyy"

# Would you like to use another custom folder than $ZSH/custom?
# ZSH_CUSTOM=/path/to/new-custom-folder

# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
# Add wisely, as too many plugins slow down shell startup.
plugins=(git)

source $ZSH/oh-my-zsh.sh

# User configuration

# export MANPATH="/usr/local/man:$MANPATH"

# You may need to manually set your language environment
# export LANG=en_US.UTF-8

# Preferred editor for local and remote sessions
# if [[ -n $SSH_CONNECTION ]]; then
#   export EDITOR='vim'
# else
#   export EDITOR='mvim'
# fi

# Compilation flags
# export ARCHFLAGS="-arch x86_64"

# ssh
export SSH_KEY_PATH="~/.ssh/id_rsa"

# Path to your oh-my-zsh installation
#export LIBRARY_PATH=$LIBRARY_PATH:~/.graph_programming/lib
#export LD_LIBRARY_PATH=$LIBRARY_PATH:~/.graph_programming/lib
#export CPATH=$CPATH:~/.graph_programming/include

#man vim
export MANPAGER="/bin/sh -c \"sed -e 's/.$(echo -e '\010')//g' | nvim -R -c 'set ft=man nomod nolist' -\""

#man colors
export LESS_TERMCAP_mb=$'\e[1;31m'     # begin bold
export LESS_TERMCAP_md=$'\e[1;33m'     # begin blink
export LESS_TERMCAP_so=$'\e[01;44;37m' # begin reverse video
export LESS_TERMCAP_us=$'\e[01;37m'    # begin underline
export LESS_TERMCAP_me=$'\e[0m'        # reset bold/blink
export LESS_TERMCAP_se=$'\e[0m'        # reset reverse video
export LESS_TERMCAP_ue=$'\e[0m'        # reset underline
export GROFF_NO_SGR=1                  # for konsole and gnome-terminal

#env var color 
export COLOR_NC='\e[0m' # No Color
export COLOR_WHITE='\e[1;37m'
export COLOR_BLACK='\e[0;30m'
export COLOR_BLUE='\e[0;34m'
export COLOR_LIGHT_BLUE='\e[1;34m'
export COLOR_GREEN='\e[0;32m'
export COLOR_LIGHT_GREEN='\e[1;32m'
export COLOR_CYAN='\e[0;36m'
export COLOR_LIGHT_CYAN='\e[1;36m'
export COLOR_RED='\e[0;31m'
export COLOR_LIGHT_RED='\e[1;31m'
export COLOR_PURPLE='\e[0;35m'
export COLOR_LIGHT_PURPLE='\e[1;35m'
export COLOR_BROWN='\e[0;33m'
export COLOR_YELLOW='\e[1;33m'
export COLOR_GRAY='\e[0;30m'
export COLOR_LIGHT_GRAY='\e[0;37m'


# Set personal aliases, overriding those provided by oh-my-zsh libs,
# plugins, and themes. Aliases can be placed here, though oh-my-zsh
# users are encouraged to define aliases within the ZSH_CUSTOM folder.
# For a full list of active aliases, run `alias`.
#
# Example aliases

alias ls="exa"
alias l="exa -l"
alias ll="exa -la"
alias t="exa --tree -Icmake-build-debug -Ibuild -I.git"
alias tt="exa --tree -a -I.git"
alias vim="nvim"
alias vi="vim"
alias v="vim"
#alias make="make -j3"
#alias gcc="gcc -Wall -Wextra"
alias us="setxkbmap us"
alias fr="setxkbmap fr"
#alias make="colormake"
alias run="./manage.py runserver"
alias migrate="./manage.py makemigrations && ./manage.py migrate"
alias update_dotfiles="cd ~/git/gitgit/dotfiles/ && git add -A && git commit -m 'update' && git push && cd -"

alias backlight="sudo tee /sys/class/backlight/intel_backlight/brightness <<< 933"
alias wificode="sudo grep -r '^psk=' /etc/NetworkManager/system-connections/"

alias gen="cat ~/Documents/mca.txt | grep"

alias zshrc="nvim ~/.zshrc ; source ~/.zshrc"
alias vimrc="nvim  ~/.config/nvim/init.vim"

alias update="sudo pacman -Syu"
alias work="cd ~/git/bnblord/bnbstaff; workon bnbstaff"
alias runserver="./manage.py runserver"

matrix() {
    echo -e "\e[1;40m" ;
    clear ;
    while :;
    do echo $LINES $COLUMNS $(( $RANDOM % $COLUMNS)) $(( $RANDOM % 72 )) ;
	sleep 0.05;
    done|awk '{ letters="abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789@#$%^&*()"; c=$4; letter=substr(letters,c,1);a[$3]=0;for (x in a) {o=a[x];a[x]=a[x]+1; printf "\033[%s;%sH\033[2;32m%s",o,x,letter; printf "\033[%s;%sH\033[1;37m%s\033[0;0H",a[x],x,letter;if (a[x] >= $1) { a[x]=0; } }}';
}
# Disable bios beep
xset b off

source ~/.zshrc.secret
[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

# The next line updates PATH for the Google Cloud SDK.
if [ -f '/home/erwanbernard/git/wediagnostix/google-cloud-sdk/path.zsh.inc' ]; then . '/home/erwanbernard/git/wediagnostix/google-cloud-sdk/path.zsh.inc'; fi

# The next line enables shell command completion for gcloud.
if [ -f '/home/erwanbernard/git/wediagnostix/google-cloud-sdk/completion.zsh.inc' ]; then . '/home/erwanbernard/git/wediagnostix/google-cloud-sdk/completion.zsh.inc'; fi
