name: Reusable workflow

on: workflow_call

jobs:
  example_job:
    name: Pass input and secrets to my-action
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2

  test-run-worfklow-call:
    uses: './.github/workflows/test-workflow.yaml'
